logging:
  level:
    org:
      apache:
        http: "DEBUG"
    reactor:
      netty:
        http:
          client: "DEBUG"

server:
  port: 8082

kafka:
  url: localhost:9092
  topicname: courses-manager

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      path-mapping:
        health: "-"
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          additional-path: "server:/healthy"
          show-components: always
          include: livenessState
        readiness:
          additional-path: "server:/ready"
          show-components: always
          include: readinessState

spring:
  datasource:
    url: jdbc:h2:mem:carrefourDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
