CREATE TABLE IF NOT EXISTS delivery (id INT NOT NULL AUTO_INCREMENT, CUSTOMER_ID NUMBER, DELIVERY_OPTION VARCHAR(255), PRIMARY KEY (id));


CREATE TABLE IF NOT EXISTS AVAILABLE_TIME_SLOT (id INT NOT NULL, START_TIME VARCHAR(20), END_TIME VARCHAR(20), NUMBER_OF_RESERVATION NUMBER, NUMBER_MAX_OF_RESERVATION NUMBER, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS time_slot (id INT NOT NULL AUTO_INCREMENT, START_TIME VARCHAR(20), END_TIME VARCHAR(20), SLOT_ID NUMBER, CUSTOMER_ID NUMBER, PRIMARY KEY (id));


